[package]
name = "ipfs_uploader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-api-backend-hyper = "0.5"
tokio = { version = "1.2", features= ["full"]}
web3 = "0.17.0"
clap = "~3.0.0-beta.1"
